import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "@tanstack/react-router";
import { motion } from "framer-motion";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import { Badge, Button, Card, IconBox } from "@/components/lab";
import { Container } from "@/components/layout/Container";
import { hero } from "@/data/landing";
import { photos } from "@/data/images";
import { fadeUp, levitate, scaleIn, staggerContainer } from "@/lib/motion";
import { DashboardMockup } from "./Mockups";
import { Photo } from "./Photo";
export function Hero() {
    return (_jsxs("section", { className: "relative overflow-hidden pt-10 pb-20 sm:pt-16", children: [_jsx("div", { className: "halo halo-drift -top-32 -left-24 size-[28rem] bg-mint-200/70" }), _jsx("div", { className: "halo halo-drift top-40 -right-32 size-[26rem] bg-accent-lime/30" }), _jsxs(Container, { className: "relative grid items-center gap-12 lg:grid-cols-[1.05fr_1fr]", children: [_jsxs(motion.div, { variants: staggerContainer(0.08), initial: "hidden", animate: "show", className: "flex flex-col items-start gap-6", children: [_jsx(motion.div, { variants: fadeUp, children: _jsx(Badge, { variant: "lime", dot: true, children: hero.badge }) }), _jsxs(motion.h1, { variants: fadeUp, className: "text-4xl leading-[1.05] font-extrabold text-ink-900 sm:text-5xl lg:text-6xl", children: ["Digitalisez tout le cycle d'analyse de votre", " ", _jsx("span", { className: "text-brand-600", children: "laboratoire" })] }), _jsx(motion.p, { variants: fadeUp, className: "max-w-xl text-lg text-muted-foreground", children: hero.subtitle }), _jsxs(motion.div, { variants: fadeUp, className: "flex flex-wrap gap-3", children: [_jsx(Link, { to: "/integration", children: _jsx(Button, { size: "lg", icon: _jsx(ArrowRight, { className: "size-4", "aria-hidden": "true" }), children: hero.primaryCta }) }), _jsx("a", { href: "#workflow", children: _jsx(Button, { size: "lg", variant: "secondary", children: hero.secondaryCta }) })] }), _jsx(motion.ul, { variants: fadeUp, className: "flex flex-wrap gap-x-5 gap-y-2 text-sm text-ink-900/80", children: ["Multi-laboratoires", "Double validation", "Audit immuable"].map((t) => (_jsxs("li", { className: "flex items-center gap-1.5", children: [_jsx(CheckCircle2, { className: "size-4 text-brand-600", "aria-hidden": "true" }), t] }, t))) })] }), _jsxs(motion.div, { variants: scaleIn, initial: "hidden", animate: "show", className: "relative", children: [_jsx(Photo, { eager: true, src: photos.teamLab.src, alt: photos.teamLab.alt, className: "aspect-[4/3.4] w-full" }), _jsx(motion.div, { ...levitate(8, 6), className: "absolute -bottom-10 -left-4 w-[78%] sm:-left-10 sm:w-[62%]", children: _jsx(DashboardMockup, {}) })] })] }), _jsx(Container, { className: "relative mt-24 lg:mt-20", children: _jsx(motion.div, { variants: staggerContainer(0.08), initial: "hidden", whileInView: "show", viewport: { once: true, amount: 0.3 }, className: "grid gap-4 md:grid-cols-3", children: hero.bento.map((b, i) => (_jsx(motion.div, { variants: fadeUp, children: _jsxs(Card, { variant: i === 1 ? "dark" : "glossy", className: "hover-lift flex h-full items-start gap-4", children: [_jsx(IconBox, { icon: b.icon, variant: i === 1 ? "lime" : "mint" }), _jsxs("div", { children: [_jsx("h3", { className: "font-bold", children: b.title }), _jsx("p", { className: i === 1 ? "mt-1 text-sm text-primary-foreground/75" : "mt-1 text-sm text-muted-foreground", children: b.description })] })] }) }, b.title))) }) })] }));
}
