import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "@tanstack/react-router";
import { motion } from "framer-motion";
import { ArrowRight, Check, KeyRound, ShieldCheck } from "lucide-react";
import { Accordion, Badge, Button, Card, Carousel, IconBox, Reveal, SectionHeader, StatCard, Stepper, } from "@/components/lab";
import { Section } from "@/components/layout/Section";
import { ai, automation, cta, domains, faq, features, requestStatuses, roles, security, stats, validation, workflowSteps, } from "@/data/landing";
import { photos } from "@/data/images";
import { fadeUp, levitate, slideInLeft, slideInRight, staggerContainer, } from "@/lib/motion";
import { AiMockup, ValidationMockup } from "./Mockups";
import { Photo } from "./Photo";
const grid = (cls) => ({
    className: cls,
    variants: staggerContainer(0.07),
    initial: "hidden",
    whileInView: "show",
    viewport: { once: true, amount: 0.15 },
});
export function Stats() {
    return (_jsx(Section, { tone: "card", className: "py-16 sm:py-16", children: _jsx("div", { className: "grid grid-cols-2 gap-4 lg:grid-cols-4", children: stats.map((s) => (_jsx(StatCard, { ...s }, s.label))) }) }));
}
export function Features() {
    return (_jsxs(Section, { id: "fonctionnalites", children: [_jsx(SectionHeader, { eyebrow: "Fonctionnalit\u00E9s", title: "Tous les modules d'un LIMS moderne", description: "Chaque module est pens\u00E9 pour les contraintes r\u00E9elles d'un laboratoire accr\u00E9dit\u00E9." }), _jsxs("div", { className: "mt-14 grid items-stretch gap-6 lg:grid-cols-[1fr_2fr]", children: [_jsx(Reveal, { className: "hidden lg:block", children: _jsx(Photo, { src: photos.scientistLab.src, alt: photos.scientistLab.alt, className: "h-full min-h-96" }) }), _jsx(motion.div, { ...grid("grid gap-4 sm:grid-cols-2 lg:grid-cols-3"), children: features.map((f) => (_jsx(motion.div, { variants: fadeUp, children: _jsxs(Card, { variant: "flat", className: "group hover-lift h-full", children: [_jsx(IconBox, { icon: f.icon, className: "transition-transform group-hover:scale-110" }), _jsx("h3", { className: "mt-4 font-bold text-ink-900", children: f.title }), _jsx("p", { className: "mt-1.5 text-sm text-muted-foreground", children: f.description })] }) }, f.title))) })] })] }));
}
export function WorkflowSection() {
    return (_jsxs(Section, { id: "workflow", tone: "alt", children: [_jsx(SectionHeader, { eyebrow: "Workflow", title: "Neuf \u00E9tapes, de la demande \u00E0 la cl\u00F4ture", description: "Un parcours lin\u00E9aire et contr\u00F4l\u00E9 : chaque \u00E9tape est horodat\u00E9e et attribu\u00E9e." }), _jsx(Stepper, { steps: workflowSteps, className: "mt-14" }), _jsx(Reveal, { className: "mt-14", children: _jsxs(Card, { variant: "glass", className: "flex flex-col gap-4", children: [_jsx("p", { className: "text-sm font-bold text-ink-900", children: "Statuts d'une demande" }), _jsx("div", { className: "flex flex-wrap gap-2", children: requestStatuses.map((s, i) => (_jsx(Badge, { size: "sm", variant: i < 5 ? (i === 4 ? "lime" : "mint") : "outline", children: s }, s))) })] }) })] }));
}
export function Roles() {
    return (_jsxs(Section, { id: "roles", children: [_jsx(SectionHeader, { eyebrow: "Espaces par r\u00F4le", title: "Six r\u00F4les, six espaces d\u00E9di\u00E9s", description: "Chacun ne voit que ce dont il a besoin, avec les droits strictement n\u00E9cessaires." }), _jsx(Carousel, { ariaLabel: "R\u00F4les utilisateurs", className: "mt-12", children: roles.map((r) => (_jsxs(Card, { variant: "glossy", padding: "lg", className: "h-full", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx(IconBox, { icon: r.icon, variant: "brand", size: "lg" }), r.twoFactor && (_jsx(Badge, { size: "sm", variant: "lime", icon: _jsx(KeyRound, { className: "size-3", "aria-hidden": "true" }), children: "2FA" }))] }), _jsx("h3", { className: "mt-5 text-xl font-bold text-ink-900", children: r.role }), _jsx("ul", { className: "mt-4 flex flex-col gap-2.5", children: r.capabilities.map((c) => (_jsxs("li", { className: "flex gap-2 text-sm text-muted-foreground", children: [_jsx(Check, { className: "mt-0.5 size-4 shrink-0 text-brand-600", "aria-hidden": "true" }), c] }, c))) })] }, r.role))) })] }));
}
export function Validation() {
    return (_jsx(Section, { tone: "mint", children: _jsxs("div", { className: "grid items-center gap-14 lg:grid-cols-2", children: [_jsxs(Reveal, { variants: slideInLeft, className: "flex flex-col gap-5", children: [_jsx(Badge, { variant: "lime", dot: true, className: "self-start", children: validation.eyebrow }), _jsx("h2", { className: "text-3xl font-extrabold text-ink-900 sm:text-4xl", children: validation.title }), _jsx("p", { className: "text-muted-foreground", children: validation.description }), _jsx("ul", { className: "flex flex-col gap-3", children: validation.points.map((p) => (_jsxs("li", { className: "flex gap-3 text-sm text-ink-900", children: [_jsx("span", { className: "flex size-6 shrink-0 items-center justify-center rounded-full bg-accent-lime", children: _jsx(Check, { className: "size-3.5", "aria-hidden": "true" }) }), p] }, p))) })] }), _jsxs(Reveal, { variants: slideInRight, className: "relative", children: [_jsx(Photo, { src: validation.photo.src, alt: validation.photo.alt, className: "aspect-[4/3] w-full" }), _jsx(motion.div, { ...levitate(6, 5), className: "absolute -bottom-10 -right-2 w-[75%] sm:-right-8 sm:w-[60%]", children: _jsx(ValidationMockup, {}) }), validation.floating.map((f, i) => (_jsxs(motion.div, { ...levitate(5, 4 + i), className: i === 0
                                ? "glass-card absolute top-4 -left-3 flex items-center gap-2 rounded-2xl px-3 py-2 text-xs font-semibold text-brand-900 sm:-left-8"
                                : "glass-card absolute top-24 -left-3 hidden items-center gap-2 rounded-2xl px-3 py-2 text-xs font-semibold text-brand-900 sm:-left-12 sm:flex", children: [_jsx(f.icon, { className: "size-4 text-brand-600", "aria-hidden": "true" }), f.label] }, f.label)))] })] }) }));
}
export function AiSection() {
    return (_jsx(Section, { id: "ia", children: _jsxs("div", { className: "grid items-center gap-14 lg:grid-cols-[1fr_1.1fr]", children: [_jsxs("div", { children: [_jsx(SectionHeader, { align: "left", eyebrow: ai.eyebrow, title: ai.title, description: ai.description }), _jsx(motion.div, { ...grid("mt-8 flex flex-col gap-4"), children: ai.cards.map((c) => (_jsx(motion.div, { variants: fadeUp, children: _jsxs(Card, { variant: "flat", padding: "md", className: "hover-lift flex gap-4", children: [_jsx(IconBox, { icon: c.icon, variant: "lime", shape: "circle" }), _jsxs("div", { children: [_jsx("h3", { className: "font-bold text-ink-900", children: c.title }), _jsx("p", { className: "mt-1 text-sm text-muted-foreground", children: c.description })] })] }) }, c.title))) }), _jsx(Reveal, { className: "mt-5", children: _jsxs("p", { className: "flex items-start gap-2 rounded-2xl bg-surface-card p-4 text-sm font-semibold text-brand-900", children: [_jsx(ShieldCheck, { className: "size-5 shrink-0", "aria-hidden": "true" }), ai.notice] }) })] }), _jsxs(Reveal, { variants: slideInRight, className: "relative", children: [_jsx(Photo, { src: photos.cells.src, alt: photos.cells.alt, className: "aspect-square w-full" }), _jsx(motion.div, { ...levitate(7, 6), className: "absolute inset-x-6 bottom-6 sm:inset-x-auto sm:right-6 sm:w-[70%]", children: _jsx(AiMockup, {}) })] })] }) }));
}
export function Automation() {
    return (_jsxs(Section, { tone: "alt", children: [_jsx(SectionHeader, { eyebrow: automation.eyebrow, title: automation.title, description: automation.description }), _jsxs(motion.div, { ...grid("mt-14 grid items-center gap-4 lg:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr]"), children: [automation.chain.map((c) => (_jsxs(motion.div, { variants: fadeUp, className: "contents", children: [_jsxs(Card, { variant: "glossy", className: "text-center", children: [_jsx(IconBox, { icon: c.icon, variant: "brand", className: "mx-auto" }), _jsx("h3", { className: "mt-3 font-bold text-ink-900", children: c.title }), _jsx("p", { className: "text-sm text-muted-foreground", children: c.description })] }), _jsx(ArrowRight, { className: "mx-auto size-5 rotate-90 text-brand-600 lg:rotate-0", "aria-hidden": "true" })] }, c.title))), _jsx(motion.div, { variants: fadeUp, children: _jsxs(Card, { variant: "dark", className: "flex flex-col gap-2", children: [_jsx("p", { className: "text-sm font-bold", children: "Notifications" }), automation.channels.map((ch) => (_jsxs("span", { className: "flex items-center gap-2 rounded-xl bg-primary-foreground/10 px-3 py-2 text-sm", children: [_jsx(ch.icon, { className: "size-4 text-accent-lime", "aria-hidden": "true" }), ch.label] }, ch.label)))] }) })] })] }));
}
export function Security() {
    return (_jsxs(Section, { id: "securite", children: [_jsx(SectionHeader, { eyebrow: security.eyebrow, title: security.title, description: security.description }), _jsxs("div", { className: "mt-14 grid gap-6 lg:grid-cols-[1fr_1.6fr]", children: [_jsx(Reveal, { children: _jsx(Photo, { src: security.photo.src, alt: security.photo.alt, className: "h-full min-h-72" }) }), _jsx(motion.div, { ...grid("grid gap-4 sm:grid-cols-2"), children: security.cards.map((c) => (_jsx(motion.div, { variants: fadeUp, children: _jsxs(Card, { variant: "bento", className: "hover-lift h-full", children: [_jsx(IconBox, { icon: c.icon, variant: "mint" }), _jsx("h3", { className: "mt-3 font-bold text-ink-900", children: c.title }), _jsx("p", { className: "mt-1 text-sm text-muted-foreground", children: c.description })] }) }, c.title))) })] })] }));
}
export function Domains() {
    return (_jsxs(Section, { id: "domaines", tone: "card", children: [_jsx(SectionHeader, { eyebrow: "Domaines", title: "Un LIMS pour chaque type de laboratoire" }), _jsx(motion.div, { ...grid("mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"), children: domains.map((d) => (_jsxs(motion.article, { variants: fadeUp, className: "group hover-lift overflow-hidden rounded-3xl bg-card shadow-soft", children: [_jsx(Photo, { src: d.photo.src, alt: d.photo.alt, className: "aspect-[4/3] rounded-b-none border-0 shadow-none", imgClassName: "transition-transform duration-500 group-hover:scale-105" }), _jsxs("div", { className: "p-5", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-sm font-extrabold text-brand-600", children: d.number }), _jsx(IconBox, { icon: d.icon, size: "sm", variant: "lime", shape: "circle" })] }), _jsx("h3", { className: "mt-2 text-lg font-bold text-ink-900", children: d.title }), _jsx("div", { className: "mt-3 flex flex-wrap gap-1.5", children: d.examples.map((e) => (_jsx(Badge, { size: "sm", variant: "soft", children: e }, e))) })] })] }, d.title))) })] }));
}
export function Faq() {
    return (_jsx(Section, { id: "faq", children: _jsxs("div", { className: "grid gap-12 lg:grid-cols-[1fr_1.4fr]", children: [_jsxs("div", { className: "flex flex-col gap-6", children: [_jsx(SectionHeader, { align: "left", eyebrow: "FAQ", title: "Questions fr\u00E9quentes" }), _jsx(Reveal, { className: "hidden lg:block", children: _jsx(Photo, { src: photos.microscopes.src, alt: photos.microscopes.alt, className: "aspect-[4/3]" }) })] }), _jsx(Reveal, { children: _jsx(Accordion, { items: faq }) })] }) }));
}
export function FinalCta() {
    return (_jsx(Section, { className: "pt-0", children: _jsx(Reveal, { children: _jsxs("div", { className: "glossy-top relative overflow-hidden rounded-[2rem] bg-brand-900 px-6 py-16 text-center sm:px-12", children: [_jsx("div", { className: "halo halo-drift -top-20 -left-10 size-72 bg-brand-600/60" }), _jsx("div", { className: "halo halo-drift -right-10 -bottom-24 size-72 bg-accent-lime/30" }), _jsxs("div", { className: "relative mx-auto flex max-w-2xl flex-col items-center gap-5", children: [_jsx("h2", { className: "text-3xl font-extrabold text-primary-foreground sm:text-4xl", children: cta.title }), _jsx("p", { className: "text-primary-foreground/75", children: cta.description }), _jsx(Link, { to: "/integration", children: _jsx(Button, { variant: "lime", size: "lg", icon: _jsx(ArrowRight, { className: "size-4", "aria-hidden": "true" }), children: cta.button }) })] })] }) }) }));
}
