/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as IntegrationRouteImport } from './routes/integration';
import { Route as LoginRouteImport } from './routes/login';
import { Route as UiKitRouteImport } from './routes/ui-kit';
import { Route as TestConnexionRouteImport } from './routes/test-connexion';
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const IntegrationRoute = IntegrationRouteImport.update({
    id: '/integration',
    path: '/integration',
    getParentRoute: () => rootRouteImport,
});
const LoginRoute = LoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => rootRouteImport,
});
const UiKitRoute = UiKitRouteImport.update({
    id: '/ui-kit',
    path: '/ui-kit',
    getParentRoute: () => rootRouteImport,
});
const TestConnexionRoute = TestConnexionRouteImport.update({
    id: '/test-connexion',
    path: '/test-connexion',
    getParentRoute: () => rootRouteImport,
});
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    IntegrationRoute: IntegrationRoute,
    LoginRoute: LoginRoute,
    UiKitRoute: UiKitRoute,
    TestConnexionRoute: TestConnexionRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
