/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivationRouteImport } from './routes/activation'
import { Route as ActiverCompteRouteImport } from './routes/activer-compte'
import { Route as AppRouteImport } from './routes/app'
import { Route as CarteRouteImport } from './routes/carte'
import { Route as ChangerMotDePasseRouteImport } from './routes/changer-mot-de-passe'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as IntegrationRouteImport } from './routes/integration'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UiKitRouteImport } from './routes/ui-kit'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as LaboratoiresIndexRouteImport } from './routes/laboratoires/index'
import { Route as LaboratoiresIdRouteImport } from './routes/laboratoires/$id'
import { Route as AppDemandesIntegrationIndexRouteImport } from './routes/app/demandes-integration/index'
import { Route as AppDemandesIntegrationIdRouteImport } from './routes/app/demandes-integration/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivationRoute = ActivationRouteImport.update({
  id: '/activation',
  path: '/activation',
  getParentRoute: () => rootRouteImport,
} as any)
const ActiverCompteRoute = ActiverCompteRouteImport.update({
  id: '/activer-compte',
  path: '/activer-compte',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteRoute = CarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangerMotDePasseRoute = ChangerMotDePasseRouteImport.update({
  id: '/changer-mot-de-passe',
  path: '/changer-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationRoute = IntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UiKitRoute = UiKitRouteImport.update({
  id: '/ui-kit',
  path: '/ui-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const LaboratoiresIndexRoute = LaboratoiresIndexRouteImport.update({
  id: '/laboratoires/',
  path: '/laboratoires/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratoiresIdRoute = LaboratoiresIdRouteImport.update({
  id: '/laboratoires/$id',
  path: '/laboratoires/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDemandesIntegrationIndexRoute =
  AppDemandesIntegrationIndexRouteImport.update({
    id: '/demandes-integration/',
    path: '/demandes-integration/',
    getParentRoute: () => AppRoute,
  } as any)
const AppDemandesIntegrationIdRoute =
  AppDemandesIntegrationIdRouteImport.update({
    id: '/demandes-integration/$id',
    path: '/demandes-integration/$id',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activation': typeof ActivationRoute
  '/activer-compte': typeof ActiverCompteRoute
  '/app': typeof AppRouteWithChildren
  '/carte': typeof CarteRoute
  '/changer-mot-de-passe': typeof ChangerMotDePasseRoute
  '/inscription': typeof InscriptionRoute
  '/integration': typeof IntegrationRoute
  '/login': typeof LoginRoute
  '/ui-kit': typeof UiKitRoute
  '/laboratoires/$id': typeof LaboratoiresIdRoute
  '/app/': typeof AppIndexRoute
  '/laboratoires/': typeof LaboratoiresIndexRoute
  '/app/demandes-integration/$id': typeof AppDemandesIntegrationIdRoute
  '/app/demandes-integration/': typeof AppDemandesIntegrationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activation': typeof ActivationRoute
  '/activer-compte': typeof ActiverCompteRoute
  '/carte': typeof CarteRoute
  '/changer-mot-de-passe': typeof ChangerMotDePasseRoute
  '/inscription': typeof InscriptionRoute
  '/integration': typeof IntegrationRoute
  '/login': typeof LoginRoute
  '/ui-kit': typeof UiKitRoute
  '/laboratoires/$id': typeof LaboratoiresIdRoute
  '/app': typeof AppIndexRoute
  '/laboratoires': typeof LaboratoiresIndexRoute
  '/app/demandes-integration/$id': typeof AppDemandesIntegrationIdRoute
  '/app/demandes-integration': typeof AppDemandesIntegrationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activation': typeof ActivationRoute
  '/activer-compte': typeof ActiverCompteRoute
  '/app': typeof AppRouteWithChildren
  '/carte': typeof CarteRoute
  '/changer-mot-de-passe': typeof ChangerMotDePasseRoute
  '/inscription': typeof InscriptionRoute
  '/integration': typeof IntegrationRoute
  '/login': typeof LoginRoute
  '/ui-kit': typeof UiKitRoute
  '/laboratoires/$id': typeof LaboratoiresIdRoute
  '/app/': typeof AppIndexRoute
  '/laboratoires/': typeof LaboratoiresIndexRoute
  '/app/demandes-integration/$id': typeof AppDemandesIntegrationIdRoute
  '/app/demandes-integration/': typeof AppDemandesIntegrationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activation'
    | '/activer-compte'
    | '/app'
    | '/carte'
    | '/changer-mot-de-passe'
    | '/inscription'
    | '/integration'
    | '/login'
    | '/ui-kit'
    | '/laboratoires/$id'
    | '/app/'
    | '/laboratoires/'
    | '/app/demandes-integration/$id'
    | '/app/demandes-integration/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activation'
    | '/activer-compte'
    | '/carte'
    | '/changer-mot-de-passe'
    | '/inscription'
    | '/integration'
    | '/login'
    | '/ui-kit'
    | '/laboratoires/$id'
    | '/app'
    | '/laboratoires'
    | '/app/demandes-integration/$id'
    | '/app/demandes-integration'
  id:
    | '__root__'
    | '/'
    | '/activation'
    | '/activer-compte'
    | '/app'
    | '/carte'
    | '/changer-mot-de-passe'
    | '/inscription'
    | '/integration'
    | '/login'
    | '/ui-kit'
    | '/laboratoires/$id'
    | '/app/'
    | '/laboratoires/'
    | '/app/demandes-integration/$id'
    | '/app/demandes-integration/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivationRoute: typeof ActivationRoute
  ActiverCompteRoute: typeof ActiverCompteRoute
  AppRoute: typeof AppRouteWithChildren
  CarteRoute: typeof CarteRoute
  ChangerMotDePasseRoute: typeof ChangerMotDePasseRoute
  InscriptionRoute: typeof InscriptionRoute
  IntegrationRoute: typeof IntegrationRoute
  LoginRoute: typeof LoginRoute
  UiKitRoute: typeof UiKitRoute
  LaboratoiresIdRoute: typeof LaboratoiresIdRoute
  LaboratoiresIndexRoute: typeof LaboratoiresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activation': {
      id: '/activation'
      path: '/activation'
      fullPath: '/activation'
      preLoaderRoute: typeof ActivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activer-compte': {
      id: '/activer-compte'
      path: '/activer-compte'
      fullPath: '/activer-compte'
      preLoaderRoute: typeof ActiverCompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte': {
      id: '/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof CarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changer-mot-de-passe': {
      id: '/changer-mot-de-passe'
      path: '/changer-mot-de-passe'
      fullPath: '/changer-mot-de-passe'
      preLoaderRoute: typeof ChangerMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration': {
      id: '/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof IntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-kit': {
      id: '/ui-kit'
      path: '/ui-kit'
      fullPath: '/ui-kit'
      preLoaderRoute: typeof UiKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/laboratoires/': {
      id: '/laboratoires/'
      path: '/laboratoires'
      fullPath: '/laboratoires/'
      preLoaderRoute: typeof LaboratoiresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratoires/$id': {
      id: '/laboratoires/$id'
      path: '/laboratoires/$id'
      fullPath: '/laboratoires/$id'
      preLoaderRoute: typeof LaboratoiresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/demandes-integration/': {
      id: '/app/demandes-integration/'
      path: '/demandes-integration'
      fullPath: '/app/demandes-integration/'
      preLoaderRoute: typeof AppDemandesIntegrationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/demandes-integration/$id': {
      id: '/app/demandes-integration/$id'
      path: '/demandes-integration/$id'
      fullPath: '/app/demandes-integration/$id'
      preLoaderRoute: typeof AppDemandesIntegrationIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppDemandesIntegrationIdRoute: typeof AppDemandesIntegrationIdRoute
  AppDemandesIntegrationIndexRoute: typeof AppDemandesIntegrationIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppDemandesIntegrationIdRoute: AppDemandesIntegrationIdRoute,
  AppDemandesIntegrationIndexRoute: AppDemandesIntegrationIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivationRoute: ActivationRoute,
  ActiverCompteRoute: ActiverCompteRoute,
  AppRoute: AppRouteWithChildren,
  CarteRoute: CarteRoute,
  ChangerMotDePasseRoute: ChangerMotDePasseRoute,
  InscriptionRoute: InscriptionRoute,
  IntegrationRoute: IntegrationRoute,
  LoginRoute: LoginRoute,
  UiKitRoute: UiKitRoute,
  LaboratoiresIdRoute: LaboratoiresIdRoute,
  LaboratoiresIndexRoute: LaboratoiresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
