/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarteRouteImport } from './routes/carte'
import { Route as IntegrationRouteImport } from './routes/integration'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UiKitRouteImport } from './routes/ui-kit'
import { Route as LaboratoiresIndexRouteImport } from './routes/laboratoires/index'
import { Route as LaboratoiresIdRouteImport } from './routes/laboratoires/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteRoute = CarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationRoute = IntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UiKitRoute = UiKitRouteImport.update({
  id: '/ui-kit',
  path: '/ui-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratoiresIndexRoute = LaboratoiresIndexRouteImport.update({
  id: '/laboratoires/',
  path: '/laboratoires/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratoiresIdRoute = LaboratoiresIdRouteImport.update({
  id: '/laboratoires/$id',
  path: '/laboratoires/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carte': typeof CarteRoute
  '/integration': typeof IntegrationRoute
  '/login': typeof LoginRoute
  '/ui-kit': typeof UiKitRoute
  '/laboratoires/$id': typeof LaboratoiresIdRoute
  '/laboratoires/': typeof LaboratoiresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carte': typeof CarteRoute
  '/integration': typeof IntegrationRoute
  '/login': typeof LoginRoute
  '/ui-kit': typeof UiKitRoute
  '/laboratoires/$id': typeof LaboratoiresIdRoute
  '/laboratoires': typeof LaboratoiresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carte': typeof CarteRoute
  '/integration': typeof IntegrationRoute
  '/login': typeof LoginRoute
  '/ui-kit': typeof UiKitRoute
  '/laboratoires/$id': typeof LaboratoiresIdRoute
  '/laboratoires/': typeof LaboratoiresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carte'
    | '/integration'
    | '/login'
    | '/ui-kit'
    | '/laboratoires/$id'
    | '/laboratoires/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carte'
    | '/integration'
    | '/login'
    | '/ui-kit'
    | '/laboratoires/$id'
    | '/laboratoires'
  id:
    | '__root__'
    | '/'
    | '/carte'
    | '/integration'
    | '/login'
    | '/ui-kit'
    | '/laboratoires/$id'
    | '/laboratoires/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarteRoute: typeof CarteRoute
  IntegrationRoute: typeof IntegrationRoute
  LoginRoute: typeof LoginRoute
  UiKitRoute: typeof UiKitRoute
  LaboratoiresIdRoute: typeof LaboratoiresIdRoute
  LaboratoiresIndexRoute: typeof LaboratoiresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte': {
      id: '/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof CarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration': {
      id: '/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof IntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-kit': {
      id: '/ui-kit'
      path: '/ui-kit'
      fullPath: '/ui-kit'
      preLoaderRoute: typeof UiKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratoires/': {
      id: '/laboratoires/'
      path: '/laboratoires'
      fullPath: '/laboratoires/'
      preLoaderRoute: typeof LaboratoiresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratoires/$id': {
      id: '/laboratoires/$id'
      path: '/laboratoires/$id'
      fullPath: '/laboratoires/$id'
      preLoaderRoute: typeof LaboratoiresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarteRoute: CarteRoute,
  IntegrationRoute: IntegrationRoute,
  LoginRoute: LoginRoute,
  UiKitRoute: UiKitRoute,
  LaboratoiresIdRoute: LaboratoiresIdRoute,
  LaboratoiresIndexRoute: LaboratoiresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
